### ISSUE TITLE
No devices showing up

### ISSUE THREAD

**Issue by enigmacarpc** [GregoryDosh/Home-Assistant-DreamScreen-Service#18]
Hello maybe this issue is me doing something wrong but I am not seeing any DreamScreen devices showing up in Home Assistant, I have 3.

My current configuration is 

configuration.yaml

dreamscreen:
  Tried with and without timeout:5 

Also tried 

dreamscreen:
   devices:
     - dream_screen:
         address: 192.168.1.5
         timeout: 5

File structure:

Config/custom_components/dreamscreen/ all files from the clone or download link unzipped

Log error:
Log Details (ERROR)
Tue Jun 04 2019 23:03:56 GMT-0400 (Eastern Daylight Time)
Error during setup of component dreamscreen
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/dreamscreen/__init__.py", line 165, in async_setup
    configured = config[DEVICES_CONF]
KeyError: 'devices'

**Comment by J3n50m4t** [comment]
see #17 
use my PR and it will work again. 
This repo here seems inactive recently.

**Comment by enigmacarpc** [comment]
Thank you J3n50m4t I will try this tonight.

**Comment by J3n50m4t** [comment]
Any Updates?

**Comment by enigmacarpc** [comment]
Sorry, I thought your changes were introduced into the package after I update to the latest build there is still no change. I have 2 Solos and 1 DS 4K none show up.

**Comment by J3n50m4t** [comment]
The Homeassistant Dreamscreen Component is updated. We also had a Fix for the Solo, which is related to pydreamscreen and not this repo, but all should work. Could you provide the Logs? My 4k DS works perfectly on master branch

**Comment by enigmacarpc** [comment]
Installed the latest clone 

Here is the error log:
Sun Jul 07 2019 02:48:13 GMT-0400 (Eastern Daylight Time)
Error during setup of component dreamscreen
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/dreamscreen/__init__.py", line 163, in async_setup
    configured = config[DEVICES_CONF]
KeyError: 'devices'

**Comment by saurabh-bindal** [comment]
Hi,

I am also facing the same problem. enigmacarpc were you able to fix it ?

**Comment by J3n50m4t** [comment]
Which Version of HomeAssistant are you using ?


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saurabh-bindal** [comment]
I am using 0.96.5.
If I specify my Ip address then things work

**Comment by J3n50m4t** [comment]
Did you specify it before too? 
Or did the same error show up? Because @enigmacarpc shows his config with ip adress 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saurabh-bindal** [comment]
Before I just tried with 
dreamscreen:
Tried with and without timeout:5

and I was getting the same error but when I tried with IP address then things worked

**Comment by J3n50m4t** [comment]
Works if you set ip. We will enhance the auto discovery again

**Comment by enigmacarpc** [comment]
Tested tonight with one of my Solos and manually added the IP and I see the Dreamscreen Solo
