### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by yashijoe** [GregoryDosh/Home-Assistant-DreamScreen-Service#21]
Hi Gregory,

this is from the log and it is showing up many many times, do you have any clue? thanks

Log Details (ERROR)
Sun Jul 21 2019 10:50:42 GMT+0200 (CEST)

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 226, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 256, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/config/custom_components/dreamscreen/__init__.py", line 250, in state_attributes
    self.device, (pydreamscreen.DreamScreenHD, pydreamscreen.DreamScreen4K, pydreamscreen.DreamScreenSolo)
AttributeError: module 'pydreamscreen' has no attribute 'DreamScreenSolo'

**Comment by J3n50m4t** [comment]
You dont have latest pydreamscreen installed.
I made some adjustments feew commits ago, where I added a new Device (Solo). 
As this Tool here only provides the bridge to pydreamscreen, i also added it there. The Problem, the automatic installer can't pull the latest pydreamscreen yet (its just not uploaded).
### So short time fix: 
Clone [pydreamscreen](https://github.com/GregoryDosh/pydreamscreen) into your custom components directory.
Your Directory should look like 
```
config
-- custom_components
-- -- dreamscreen
-- -- pydreamscreen
```

Restart your Homeassistant and it should work. At does at least here, so there is hope. 


I will open a ticket at pydreamscreen, as it needs to be updated automatically. We need a way for this
Also Going to update the readme til its fixed.
Let me know if

**Comment by yashijoe** [comment]
Hi J3n50m4t,

first I've removed both folder from the config/custom_components folder.
Then I've done a clean installation via ssh with the following commands:

git clone https://github.com/GregoryDosh/Home-Assistant-DreamScreen-Service.git dreamscreen
git clone https://github.com/GregoryDosh/pydreamscreen pydreamscreen

Now I got the 2 folders and dreamscreen works fine as usual, but the log keep on with the above error.

Thanks for the support

**Comment by J3n50m4t** [comment]
Mmh weird.
I may have to check the version of dreamscreen I’m using. I may accidently tested an old commit.
I will reply tomorrow. If you checkout an older dreamscreen version it also should work fine (not to old ofc, you need async support ) 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by J3n50m4t** [comment]
So here I'm again.
I realized I've used commit [e0784](https://github.com/GregoryDosh/Home-Assistant-DreamScreen-Service/tree/e0784a785830be5e03e338b1e5164b8aef076395) all the time. 
But Gregory [updated](https://github.com/GregoryDosh/pydreamscreen/issues/2#event-2498238904) pydreamscreen so home assistant should pull this one. I expected it to use the local one but in my testings I didn't update dreamscreen component, so no new pull was nessesary. 
my fault. I will update everything tomorrow over here. It was a to long day.

**Comment by yashijoe** [comment]
Thank you J3n50m4t!

**Comment by J3n50m4t** [comment]
Ok. 
After few investigations: 
Over at the [pydreamscreen](https://github.com/GregoryDosh/pydreamscreen/issues/2) we didn't publish the latest changes, so pip install got v 0.0.10. 
But we added changes so its now .11
Also this repo [now requires 0.0.11 ](https://github.com/GregoryDosh/Home-Assistant-DreamScreen-Service/commit/bb77dc6a4041840e02df5ab3f2e522f8abcd69b6)of pydreamscreen.
I tested it with latest submodules in my configuration and it works. - You can find my full config [here](https://github.com/J3n50m4t/HomeAssistantConfiguration).  I got the same errors as you did, so now ii i fixed.     
I'm sorry.
