### ISSUE TITLE
HDR state and service supports

### ISSUE THREAD

**Issue by msalhi** [GregoryDosh/Home-Assistant-DreamScreen-Service#23]
Hello,

I'm using your component and you did a great job! 

Is it possible to have a state / service for the HDR option ?
with : 
state = hdr_mode: 'on' or 'off'
service =  dreamscreen.set_hdr (mode: 0 for 'off' and 1 for 'on')

That would be really nice in order to switch depending on the source of the video.

Thank you :)

**Comment by GregoryDosh** [comment]
Is that a feature available on the 4k model?  I don't believe I see that on my HD version.  In the UDP Protocol it sounds like it's called HDR Tone Remapping, is that what you're looking for?

**Comment by msalhi** [comment]
Hey Gregory, thank you for your answer.

Yes I use the 4k model and yes that's the option on the APP. This allow me to enable or not the HDR remapping depending on my source.

Regards,
Mimo

**Comment by msalhi** [comment]
Hello Gregory!

I just saw your implementation of HDR's feature. A GREAT THANK YOU!!!
I've tested it and it's working, I can get the state and enable/disable it.

I saw it only now, because the README was not updated accordingly. But I'm sure you'll do it when you'll have time. So I'm closing this issue.

Thanks again
