### ISSUE TITLE
Hassio?

### ISSUE THREAD

**Issue by eddyliao** [GregoryDosh/Home-Assistant-DreamScreen-Service#3]
So i did manage to install the custom component into hassio
I am unable to make the service work.
The ip address you mention should it has some kind of port number?
im using duckdns and lets encrypt if that matters

**Comment by GregoryDosh** [comment]
The IP address you've picked should be the internal IP address of the DreamScreen itself.  On my internal network it's 172.10.10.200.  You shouldn't need to specify the port since that is defaulted in the configuration to 8888 which I think is the default listening port of the DreamScreen itself.

**Comment by eddyliao** [comment]
Thanks Gregory! 
Manage to make it work. 
Confirm it to be working without "grouping"
I know its experimental, and you might not have devices on hand to create a group.

But is there a way to control a specific group(i have only 1, dreamscreen and 2 sidekick in a group)

**Comment by eddyliao** [comment]
Actually, got it working with grouping
Might sound dumb but i change the group:1 to 2 and it worked, even though i have only 1 group

dreamscreen:
ip_address: 192.168.1.xxx
**group: 2**

**Comment by GregoryDosh** [comment]
Unfortunately I don't have extra devices to test with, but I'm glad you got it working.  I don't know of a nice way of finding that group number and the documentation didn't seem to indicate much in that either. :-\

**Comment by GregoryDosh** [comment]
@eddyliao 
I've updated the component so it does device discovery & should hopefully allow you to send commands properly to SideKick devices and devices in different groups.  Try em out and let me know if you find any issues.
