### ISSUE TITLE
No file found '/manifest.json' (?)

### ISSUE THREAD

**Issue by guice** [GregoryDosh/Home-Assistant-DreamScreen-Service#30]
Logger it showing:

```
Logger: hacs.repository.integration.GregoryDosh.Home-Assistant-DreamScreen-Service
First occured: 10:42:45 AM (2 occurences)
Last logged: 10:42:51 AM

No file found '/manifest.json'
```

I'm not sure why. Best I can suspect is it's looking at "root" /manifest.json not relative "./" manifest.json.

Installed via HACS Version: 0.22.1
HA: 1.106.3

**Comment by J3n50m4t** [comment]
Thanks for reporting this. Same happens on my site.

**Comment by J3n50m4t** [comment]
fixed in https://github.com/GregoryDosh/Home-Assistant-DreamScreen-Service/commit/4c672c3c8e22ee246cc7e74190895b785754275c
BREAKING CHANGE FOR ALL NON HACS USER
