### ISSUE TITLE
Issue with newest version of Home Assistant

### ISSUE THREAD

**Issue by Mibix** [GregoryDosh/Home-Assistant-DreamScreen-Service#50]
Not sure what is going on but since updating to the newest version (Home Assistant 2023.8.4 Supervisor 2023.08.1) whenever I have the integration configured in my configuration.yaml and reboot, it will not load the web ui.

**Comment by zanix** [comment]
I'm running on 2023.8.4 in a docker container and I have no issues.
Hopefully there isn't an issue with running this under the supervisor version.

**Comment by Mibix** [comment]
> I'm running on 2023.8.4 in a docker container and I have no issues. Hopefully there isn't an issue with running this under the supervisor version.

I think I figured out the issue.  I had my timeout set to 60 and one of them was not plugged in so it might have halted something in the startup.  I guess timeout is in minutes and not seconds?  Was also a bad timing mine was unplugged when I updated, heh.

**Comment by zanix** [comment]
My timeout is not set so it's the default `1` and as far as I can tell the the timeout is in seconds.
I don't see any reason why this would hold up HA itself if it was unplugged.

**Comment by Mibix** [comment]
> My timeout is not set so it's the default `1` and as far as I can tell the the timeout is in seconds. I don't see any reason why this would hold up HA itself if it was unplugged.

Yeah, I don't know it was still running HA too, could see it in the logs but could not access the web interface.
