### ISSUE TITLE
update to 0.77.3

### ISSUE THREAD

**Issue by dpdamian** [GregoryDosh/Home-Assistant-DreamScreen-Service#9]
Hi, I recently updated my home assistant to 0.77.3 and it broke my dreamscreen connection. Now all of my sensors are not reading and no commands are being sent to the dreamscreen. Any idea what broke this and methods to fix? I had a tough time piecing together the steps to install initially and am blanking on all the steps to re-install and see if that would fix.

**Comment by Jossleras** [comment]
Same here, I haven't been able to make it work again

**Comment by GregoryDosh** [comment]
I'll take a look when I can. I'm unfortunately in the middle of an unplanned housing project and my internet/desktop are out of commission for now.

**Comment by Jossleras** [comment]
Thanks a lot,  I use your component everyday!

**Comment by CMaxim77** [comment]
Are you guys using this with HassOs?

**Comment by Jossleras** [comment]
Yes, I'm running the latest version of hassio

**Comment by CMaxim77** [comment]
Me too, I was just wondering because I haven’t figured out how to install it before even updating hass. I’m newer to HA and unfortunately I couldn’t install this using terminal. I did add the files to custom_components/dreamscreen in my www (local) folder and added dreamscreen: + the IP address. But haven’t gotten dreamscreen.dreamscreen to show up. 

Hopefully a fix is on the way after he gets settled.

**Comment by JasonEMartin** [comment]
Just to clarify, rather than an issue with home assistant updates, I am pretty sure that the latest update to the DreamScreen 4K firmware, causes it to not appear via the emulated hue. 
Using http://yourHA_IPaddress/api/pi/lights does not display the dreamscreen whereas it did on the old firmware.

**Comment by dpdamian** [comment]
I am able to send python commands through my computer to still contact the dreamscreen though so I am not sure the latest update would've broken this, but not that.

**Comment by JasonEMartin** [comment]
This is from the error log, 
"Invalid service data for dreamscreen.set_mode: required key not provided @ data['entity_id']. Got None
required key not provided @ data['mode']. Got None"

**Comment by CMaxim77** [comment]
@JasonEMartin, does your Dreamscreen work properly? I can’t even get my colors to sync properly! If I put it in sleep mode one of the leds remains on. I’ve replaced the flex leds with new ones and purchased a diy cable. Still nothing but problems with this setup. Flickering leds and different colors even in static mode. This product wasn’t ready for public release yet. And I got no helpful support on the forum. I just wondered how your experience has been.

**Comment by JasonEMartin** [comment]
Hi CMaxim77, I've not had any real issues. I'll send you a direct email rather than hijack this thread.

**Comment by GregoryDosh** [comment]
Just an update:  Still dealing with house, moving, and internet problems so I haven't started diagnosing this yet.

**Comment by CMaxim77** [comment]
Any news on this yet? All I’m really looking for are basic on/off Home Assistant controls.

Thx

**Comment by GregoryDosh** [comment]
Sorry, I've been inattentive. I just started digging in again and I'm unhappy with how it's currently implemented. I'm going to give it a rewrite/update and I'll hopefully have progress soon. The underlying module (pydreamscreen) was hard coded to a byte response that changed during firmware updates I believe. It was warned it could change so I want to make it more robust. On top of making the config for the home assistant service a little easier to manage (on top of supporting more devices).

**Comment by CMaxim77** [comment]
It’s all good, you should never apologize for anything on this open source project! I appreciate you taking your time and trying to get it all back up and running! Thanks for letting me know a fix is in the works! That’s awesome news! I hope you have a good day sir!

**Comment by GregoryDosh** [comment]
@CMaxim77 Are you able to give it a shot with the updated code?  I made some quick changes in the underlying dependency and I hope it fixes things short term.  Long term I do want a rewrite to make it friendlier.

**Comment by CMaxim77** [comment]
I would be happy too! I’m at work now but as soon as I get home I’ll give it a shot and let you know! Seriously I appreciate you and the work you provide!!! Give me a few hours! Thanks!!!

**Comment by Mace404** [comment]
I just updated and all is working fine again! Thanks Gregory!

**Comment by JasonEMartin** [comment]
A second confirmation here. This update has fixed things again. Many thanks for helping us out with this.

**Comment by CMaxim77** [comment]
3rd here is working great, thanks so much for giving your time to this project!

**Comment by dpdamian** [comment]
I can also confirm the new update fixed the issue and my dreamscreen is again displaying correctly. Thanks for the help on this!
